name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # 添加清理缓存步骤
    - name: Clear cache and dependencies
      run: |
        echo "Cleaning up cached dependencies..."
        sudo rm -rf ~/.npm ~/.cache/pip
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/observability-platform
        ./deploy.sh

